<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ApplicationIcon>hex.ico</ApplicationIcon>
    <AssemblyName>N01D.Hex</AssemblyName>
    <RootNamespace>N01D.Hex</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>bad-antics</Authors>
    <Description>N01D Hex Editor — binary file inspector with hacker aesthetics</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\N01D.Shared\N01D.Shared.csproj" />
  </ItemGroup>
</Project>
